### ISSUE TITLE
Arduino compiler cannot see version updates？

### ISSUE THREAD

**Issue by gooddisplayshare** [arduino/library-registry#5513] opened 2024-12-05 01:47 UTC
2024/12/04 10:40:34 Scraping https://github.com/gooddisplayshare/ESP32epdx.git
2024/12/04 10:40:34 Checking out tag: v1.0.1
2024/12/04 10:40:34 Release ESP32epdx:1.0.1 already loaded, skipping
2024/12/04 10:40:34 Checking out tag: v1.0.2
2024/12/04 10:40:34 Release ESP32epdx:1.0.1 already loaded, skipping

@per1234 , Why? v1.0.2 is not already loaded,

**Comment by per1234** [comment] 2024-12-05 02:19
Closing as duplicate of https://github.com/arduino/library-registry/issues/5480

@gooddisplayshare you have already reported this problem. We have very limited resources to dedicate to the maintenance of the Library Manager system any many tasks to complete with those resources. So you will just need to be patient until we can allocate resources to investigating your problem.

Please don't submit duplicate reports. Submitting duplicate reports is counterproductive because then we waste time dealing with the duplicates that could have instead be put to that investigation.

**Closed by per1234** 2024-12-05 02:19 UTC
Labels: type: imperfection
