### ISSUE TITLE
Library won't install from Arduino 2.0 Library Manager

### ISSUE THREAD

**Issue by joshnishikawa** [arduino/library-registry#1895] opened 2022-09-21 13:58 UTC
### Describe the problem

This library won't install from the Arduino 2.0.0 Library Manager.
https://github.com/joshnishikawa/MIDIcontroller/releases/tag/2.5.3

A message pops up briefly in the lower right that says "Processing MIDIcontroller:2.5.3" then disappears and nothing else happens.
The same library installs fine from the Arduino 1.8.19 Library Manager. Older versions of the MIDIcontroller library seem to install fine in 2.0.0 but no the 3 most recent.

### To reproduce

Search for MIDIcontroller in the Arduino 2.0.0 Library Manager. Select version 2.5.3 and click install.

### Expected behavior

Library is installed in the 'libraries' folder.

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/arduino/library-registry/issues?q=)
- [X] My report contains all necessary details

**Comment by per1234** [comment] 2022-09-23 18:50
Hi @joshnishikawa. I submitted a pull request to fix the problem with your library: https://github.com/joshnishikawa/MIDIcontroller/pull/23

We are tracking the need to make the Arduino IDE clearly communicate about the problem to the user here: https://github.com/arduino/arduino-ide/issues/621

Since the issue is not related to the content of this repository, and there are existing issues to track the problem in the library and IDE, I'll close this.

**Closed by per1234** 2022-09-23 18:50 UTC
Labels: conclusion: off topic, type: imperfection
