### ISSUE TITLE
Library release removal request

### ISSUE THREAD

**Issue by beratcomputer** [arduino/library-registry#3622] opened 2023-11-21 11:34 UTC
### Library name

Acrome SMD - Arduino Library 

### Version to remove

1.0.0

**Comment by beratcomputer** [comment] 2023-11-21 11:35
@ArduinoBot

**Comment by per1234** [comment] 2023-11-22 03:56
Hi @beratcomputer. As you already discovered, The Arduino Library Manager indexer rejects any release that has a value in the `name` field of the [`library.properties` metadata file](https://arduino.github.io/arduino-cli/latest/library-specification/#library-metadata) that does not match the value the library had at the time it was registered here.

The `name` value at the 1.0.0 release is the currently registered name [`Acrome SMD - Arduino Library`](https://github.com/Acrome-Smart-Motor-Driver/SMD-Arduino-Library/blob/1.0.0/library.properties#L1)

You have submitted a request (https://github.com/arduino/library-registry/issues/3621) to change the registered name to the new value [`Acrome-SMD`](https://github.com/Acrome-Smart-Motor-Driver/SMD-Arduino-Library/blob/1.0.1/library.properties#L1). When that request is processed, the 1.0.0 release of the library will be removed from the Library Manager index as a matter of course (since it will no longer have a `name` value matching the registered name).

So no special action is needed to accommodate this release removal request. For this reason, I'll close it as a duplicate of the name change request https://github.com/arduino/library-registry/issues/3621

**Closed by per1234** 2023-11-22 03:56 UTC
Labels: topic: release removal
