### ISSUE TITLE
No library Update

### ISSUE THREAD

**Issue by RobertByrnes** [arduino/library-registry#4809] opened 2024-07-19 19:57 UTC
Hi, I have pushed a new tag to master 1.3.0 for GovoroxSSLClient, library.properties file has this version. I have also created the release for this version. This was done on 24 hours ago. The  index is not showing this new version and is still on 1.2.0 as the latest.

Is this within a reasonable timeframe or is there an issue with the update process or the way I have used?

Cheers

**Comment by per1234** [comment] 2024-07-20 03:08
Duplicate of https://github.com/arduino/library-registry/issues/4806

**Closed by per1234** 2024-07-20 03:08 UTC
Labels: type: imperfection
