### ISSUE TITLE
[Library Manager] Please Add DIGIEDGE Frame Generator Library

### ISSUE THREAD

**Issue by HoussamElbiade** [arduino/library-registry#3166] opened 2023-08-02 11:01 UTC
Please add the following to the library manager for "Digiedge_frame_generator" with v1.1.0 release:

https://github.com/HoussamElbiade/Digiedge_frame_generator

Thanks!

**Comment by per1234** [comment] 2023-08-02 12:37
Hello @HoussamElbiade. Thanks for your interest in contributing to the Arduino Library Manager index. I see you have since discovered the new procedure we use for submitting libraries so I will close this as a duplicate of your submission pull request: https://github.com/arduino/library-registry/pull/3162

**Closed by per1234** 2023-08-02 12:37 UTC
Labels: topic: submission
