### ISSUE TITLE
Version not updated

### ISSUE THREAD

**Issue by gooddisplayshare** [arduino/library-registry#5520] opened 2024-12-06 04:10 UTC
2024/12/04 10:40:34 Scraping https://github.com/gooddisplayshare/ESP32epdx.git
2024/12/04 10:40:34 Checking out tag: v1.0.1
2024/12/04 10:40:34 Release ESP32epdx:1.0.1 already loaded, skipping
2024/12/04 10:40:34 Checking out tag: v1.0.2
2024/12/04 10:40:34 Release ESP32epdx:1.0.1 already loaded, skipping

@per1234 , 
Please do not close this message. The problem has been waiting for several days without resolution. Please urge the relevant personnel to handle it urgently.
There are no errors or prompts, but the version is not updated. What is the reason for this?
Thank 有~

**Comment by per1234** [comment] 2024-12-06 04:50
Closing as duplicate of https://github.com/arduino/library-registry/issues/5480.

@gooddisplayshare I have already asked you nicely to stop submitting duplicate issues. You are behaving in a very disrespectful manner. If you can't behave professionally and responsibly then you will be banned from all of Arduino's repositories and your library will be removed from Library Manager. This is your last warning.

**Closed by per1234** 2024-12-06 04:50 UTC
Labels: type: imperfection

**Comment by gooddisplayshare** [comment] 2024-12-06 14:34
I just want to know the reason. I don’t want to offend you. I hope you can understand. Thank you~ @per1234

**Comment by gooddisplayshare** [comment] 2024-12-09 04:07
@Per1234, can you help me? Currently, there are no error prompts in the report. I want to update the version and all steps are fine.
